### ISSUE TITLE
Fails extracting some of the downloaded source data

### ISSUE THREAD

**Issue by theviperanit** [covidgraph/data_cord19#2]
While processing it quits with an error tarfile.ReadError: not a gzip file.

**Comment by motey** [comment]
![grafik](https://user-images.githubusercontent.com/1006417/85687594-4cbb8800-b6d1-11ea-97c0-50c5b3e6a0c3.png)
looks like a bug in the downloader tool https://github.com/josephsdavid/cord-19-tools i am in contact with the developer see https://github.com/josephsdavid/cord-19-tools/issues/7 but he is busy at the moment. i will try to get my hands on the cord-19-tools the next days and fix it myself or replace the tool. but no promisses, there is a lack of time here :)

**Comment by motey** [comment]
fixed with https://github.com/covidgraph/data_cord19/releases/tag/V0.4
